#ifndef MCC_CONFIG_H
#define MCC_CONFIG_H

#define MCC_USE_HASH_TABLE_FOR_MACROS (1)

#define MCC_DEBUG (1)

#define MCC_USE_DYNAMIC_STRING_BUFFER_TOKENISER (1)

#define MCC_C99_COMPATIBLE (1)

#endif
